version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: laravel-8:0.0.1-release
    networks:
      - laravel-network
    ports:
      - 8080:80
    volumes:
      - ./.httpd/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
networks:
  laravel-network:
